<?php
session_start();

// Check if user is logged in
if (empty($_SESSION['logged_in'])) {
    header('Location: loginpage.php');
    exit;
}

// Set headers for file download
header('Content-Type: text/csv');
header('Content-Disposition: attachment; filename="RSO_Research_Report_' . date('Y-m-d_H-i-s') . '.csv"');
header('Cache-Control: no-cache, must-revalidate');
header('Expires: Sat, 26 Jul 1997 05:00:00 GMT');

// Create output stream
$output = fopen('php://output', 'w');

// Function to read CSV data
function readCSVData($file_path) {
    $data = [];
    if (file_exists($file_path)) {
        $file = fopen($file_path, 'r');
        while (($row = fgetcsv($file)) !== false) {
            if (!empty($row) && !empty(array_filter($row))) {
                $data[] = $row;
            }
        }
        fclose($file);
    }
    return $data;
}

// Function to write section header
function writeSectionHeader($output, $title) {
    fputcsv($output, ['']);
    fputcsv($output, [$title]);
    fputcsv($output, ['']);
}

// Function to write data with headers
function writeDataSection($output, $data, $headers) {
    if (!empty($data)) {
        fputcsv($output, $headers);
        foreach ($data as $row) {
            fputcsv($output, $row);
        }
    }
}

// Check for specific export type
$export_type = $_GET['type'] ?? 'comprehensive';
$include_data = $_GET['data'] ?? [];

// Write report header
$report_title = $export_type === 'comprehensive' ? 'RSO Research Management System - Comprehensive Report' : 'RSO Research Management System - Custom Report';
fputcsv($output, [$report_title]);
fputcsv($output, ['Generated on: ' . date('Y-m-d H:i:s')]);
fputcsv($output, ['Generated by: ' . ($_SESSION['user_full_name'] ?? 'Unknown User')]);
fputcsv($output, ['User Department: ' . ($_SESSION['user_department'] ?? 'Unknown Department')]);
fputcsv($output, ['']);

// Initialize data arrays
$publications = [];
$ethics = [];
$research_activities = [];
$kpi_records = [];
$data_tools = [];

// 1. Publications and Presentations
if ($export_type === 'comprehensive' || in_array('publications', $include_data)) {
    $pub_file = __DIR__ . '/publication_presentation.csv';
    $publications = readCSVData($pub_file);
    if (!empty($publications)) {
        writeSectionHeader($output, 'PUBLICATIONS AND PRESENTATIONS');
        $pub_headers = ['Date', 'Author', 'Title', 'Journal/Conference', 'DOI/ISBN', 'Status'];
        writeDataSection($output, $publications, $pub_headers);
    }
}

// 2. Ethics Reviewed Protocols
if ($export_type === 'comprehensive' || in_array('ethics', $include_data)) {
    $ethics_file = __DIR__ . '/ethics_reviewed_protocols.csv';
    $ethics = readCSVData($ethics_file);
    if (!empty($ethics)) {
        writeSectionHeader($output, 'ETHICS REVIEWED PROTOCOLS');
        $ethics_headers = ['No', 'Title', 'Department', 'Status', 'Action'];
        writeDataSection($output, $ethics, $ethics_headers);
    }
}

// 3. Research Capacity Building Activities
if ($export_type === 'comprehensive' || in_array('research', $include_data)) {
    $research_file = __DIR__ . '/research_capacity_data.csv';
    $research_activities = readCSVData($research_file);
    if (!empty($research_activities)) {
        writeSectionHeader($output, 'RESEARCH CAPACITY BUILDING ACTIVITIES');
        $research_headers = ['Date', 'Activity Title', 'Description', 'Department', 'Participants', 'Outcomes'];
        writeDataSection($output, $research_activities, $research_headers);
    }
}

// 4. KPI Records
if ($export_type === 'comprehensive' || in_array('kpi', $include_data)) {
    $kpi_file = __DIR__ . '/kpi_records.csv';
    $kpi_records = readCSVData($kpi_file);
    if (!empty($kpi_records)) {
        writeSectionHeader($output, 'KPI RECORDS');
        $kpi_headers = ['KPI Name', 'Period', 'Target', 'Actual', 'Unit', 'Score', 'Department', 'Notes'];
        writeDataSection($output, $kpi_records, $kpi_headers);
    }
}

// 5. Data Collection Tools
if ($export_type === 'comprehensive' || in_array('tools', $include_data)) {
    $dct_file = __DIR__ . '/data_collection_tools.csv';
    $data_tools = readCSVData($dct_file);
    if (!empty($data_tools)) {
        writeSectionHeader($output, 'DATA COLLECTION TOOLS');
        $dct_headers = ['Tool Name', 'Description', 'Department', 'Status', 'Last Updated'];
        writeDataSection($output, $data_tools, $dct_headers);
    }
}

// 6. Summary Statistics
writeSectionHeader($output, 'SUMMARY STATISTICS');

// Calculate statistics
$total_publications = count($publications);
$total_ethics = count($ethics);
$total_research = count($research_activities);
$total_kpi = count($kpi_records);
$total_tools = count($data_tools);

// Calculate average KPI score
$kpi_scores = [];
foreach ($kpi_records as $kpi) {
    if (isset($kpi[5]) && is_numeric($kpi[5])) {
        $kpi_scores[] = floatval($kpi[5]);
    }
}
$average_kpi = count($kpi_scores) ? round(array_sum($kpi_scores) / count($kpi_scores), 2) : 0;

// Write summary
fputcsv($output, ['Metric', 'Count']);
fputcsv($output, ['Total Publications', $total_publications]);
fputcsv($output, ['Total Ethics Protocols', $total_ethics]);
fputcsv($output, ['Total Research Activities', $total_research]);
fputcsv($output, ['Total KPI Records', $total_kpi]);
fputcsv($output, ['Total Data Collection Tools', $total_tools]);
fputcsv($output, ['Average KPI Score', $average_kpi]);

// 7. Recent Activity Summary (last 10 entries from each category)
writeSectionHeader($output, 'RECENT ACTIVITY SUMMARY (Last 10 entries per category)');

// Recent Publications
if (!empty($publications)) {
    fputcsv($output, ['Recent Publications']);
    $recent_pubs = array_slice($publications, -10);
    foreach ($recent_pubs as $pub) {
        fputcsv($output, ['Publication', $pub[0] ?? '', $pub[2] ?? '']);
    }
    fputcsv($output, ['']);
}

// Recent Research Activities
if (!empty($research_activities)) {
    fputcsv($output, ['Recent Research Activities']);
    $recent_research = array_slice($research_activities, -10);
    foreach ($recent_research as $activity) {
        fputcsv($output, ['Research Activity', $activity[0] ?? '', $activity[1] ?? '']);
    }
    fputcsv($output, ['']);
}

// Recent KPI Updates
if (!empty($kpi_records)) {
    fputcsv($output, ['Recent KPI Updates']);
    $recent_kpi = array_slice($kpi_records, -10);
    foreach ($recent_kpi as $kpi) {
        fputcsv($output, ['KPI Update', $kpi[1] ?? '', $kpi[0] ?? '', $kpi[5] ?? '']);
    }
    fputcsv($output, ['']);
}

// Close the output stream
fclose($output);
exit;
?> 